### PR TITLE
Adding time/place suggestions

### PR DESCRIPTION
**Pull request by amiakotin**
@msloes please review ;-)

### CODE REVIEW

**Comment by msloes** [comment]
boonotcool
Now we have CONFLICTS

**Comment by amiakotin** [comment]
Conflicts only appeared when @rjbez17 showed up...

**Comment by msloes** [comment]
If this can still happen I pick Wed March 1st. 7:00PM (people can show up whenever) at Eli's NE.

**Comment by rjbez17** [comment]
Put it on my calendar

**Comment by amiakotin** [comment]
Works for me

**Comment by Rooks103** [comment]
I got nothing on the calendar right now.

**Pull request merged**
